site_name: Documentación de ODEs
theme:
  name: material
nav:
  - Home: index.md
  - Reference: reference.md
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

